spring:
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/demo
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: stoneberg
    password: new1234@

    hikari:
      connection-timeout: 50000
      minimum-idle: 3
      maximum-pool-size: 5

    initialization-mode: never

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: create
    properties:
      hibernate.default_batch_fetch_size: 500
      hibernate.jdbc.lob.non_contextual_creation: true


app:
  jwt:
    secret-key: HersoulslidesawayDontlookbackinanger
    token-validity: 7200000 # 2 hours (2 X 60 X 60 X 1000)
